### ISSUE TITLE
Create github release

### ISSUE THREAD

**Issue by favoyang** [JohannesDeml/unity-ui-extensions#1]
Hi @JohannesDeml ,

Thanks for creating the awesome project to keep sync with upstream. Would please create a github release `vx.y.z`? So the package can be included in upcoming openupm registry ([sneak preview](https://beta.openupm.com)), which is a service that build package directly from git tags that conform semver.

**Comment by JohannesDeml** [comment]
Hi @favoyang,

Awesome project! Sure thing, I added a new github release. The release now also shows up on openupm (https://beta.openupm.com/packages/com.unity.uiextensions/).

Thanks for including the repo and I love the idea of the new platform, keep up the good work!

**Comment by favoyang** [comment]
awesome!
